"""testing again

Revision ID: 396453f04299
Revises: a522b7b3e709
Create Date: 2021-03-07 18:29:52.242781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396453f04299'
down_revision = 'a522b7b3e709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
