"""Conditions table

Revision ID: 7e249765204c
Revises: ef17d36c40fa
Create Date: 2021-02-27 14:35:47.149477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e249765204c'
down_revision = 'ef17d36c40fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conditions_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conditions_timestamp'))

    op.drop_table('conditions')
    # ### end Alembic commands ###
