"""visit type and chief complaint

Revision ID: 81a15636a015
Revises: 8d338ae2c1a7
Create Date: 2021-02-23 20:36:49.448971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a15636a015'
down_revision = '8d338ae2c1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visit_type', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_complaint'), ['complaint'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_visit_type'), ['visit_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_visit_type'))
        batch_op.drop_index(batch_op.f('ix_appointments_complaint'))
        batch_op.drop_column('visit_type')
        batch_op.drop_column('complaint')

    # ### end Alembic commands ###
