"""new appointments table

Revision ID: 8d338ae2c1a7
Revises: 6c866ddf3cfa
Create Date: 2021-02-23 17:52:55.648386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d338ae2c1a7'
down_revision = '6c866ddf3cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=220), nullable=True),
    sa.Column('doctor', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_timestamp'))
        batch_op.drop_index(batch_op.f('ix_appointments_start_time'))
        batch_op.drop_index(batch_op.f('ix_appointments_end_time'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
