"""deleting phone for heroku

Revision ID: 9deeaa7c7424
Revises: 396453f04299
Create Date: 2021-03-07 18:32:08.144655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9deeaa7c7424'
down_revision = '396453f04299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_phone')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_user_phone', ['phone'], unique=1)

    # ### end Alembic commands ###
