"""new columns to user table

Revision ID: c7ba77d9254d
Revises: 38d0c3a8fc48
Create Date: 2021-02-26 22:01:25.139009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ba77d9254d'
down_revision = '38d0c3a8fc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('gender')
        batch_op.drop_column('first_name')
        batch_op.drop_column('city')
        batch_op.drop_column('birthday')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
