"""surgeries table

Revision ID: ef17d36c40fa
Revises: df58020dd9d4
Create Date: 2021-02-27 14:06:20.893076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef17d36c40fa'
down_revision = 'df58020dd9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surgeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('surgery', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surgeries_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surgeries_timestamp'))

    op.drop_table('surgeries')
    # ### end Alembic commands ###
